import { createContext, useContext, useState, type ReactNode, type FormEvent } from 'react';
import { Link } from '@tanstack/react-router';
import { ArrowRight, ArrowUpRight, ChefHat, Clock3, Flame, Leaf, MapPin, Menu, MessageCircle, Minus, Phone, Plus, ShoppingBag, Sparkles, UtensilsCrossed, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { images, menuItems, restaurant, formatCAD, orderTotal, contactHref, type MenuItem } from '@/lib/restaurant';

type Actions = { order:(id?:string)=>void; contact:(method:'phone'|'whatsapp')=>void };
const ActionContext = createContext<Actions>({order:()=>{},contact:()=>{}});
const useActions = ()=>useContext(ActionContext);
const nav = [{to:'/' as const,label:'Home'}, {to:'/menu' as const,label:'Our Menu'}, {to:'/about' as const,label:'About Us'}, {to:'/gallery' as const,label:'Gallery'}, {to:'/contact' as const,label:'Contact'}];

export function RestaurantLayout({children}:{children:ReactNode}) {
 const [mobile,setMobile]=useState(false);
 const [orderOpen,setOrderOpen]=useState(false);
 const [contactMethod,setContactMethod]=useState<'phone'|'whatsapp'|null>(null);
 const [quantities,setQuantities]=useState<Record<string,number>>({});
 const [orderMessage,setOrderMessage]=useState('');
 const order=(id?:string)=>{setMobile(false);if(restaurant.orderingUrl){window.open(restaurant.orderingUrl,'_blank','noopener,noreferrer');return;} if(id)setQuantities(q=>({...q,[id]:(q[id]??0)+1})); setOrderMessage('');setOrderOpen(true);};
 const contact=(method:'phone'|'whatsapp')=>{setMobile(false); const href=contactHref(method,method==='phone'?restaurant.phone:restaurant.whatsapp); if(href){if(method==='phone')window.location.href=href;else window.open(href,'_blank','noopener,noreferrer');}else {setOrderOpen(false);setContactMethod(method);}};
 const total=orderTotal(quantities);
 const change=(id:string,delta:number)=>setQuantities(q=>({...q,[id]:Math.max(0,(q[id]??0)+delta)}));
 const sendOrder=()=>{const text=menuItems.filter(i=>(quantities[i.id]??0)>0).map(i=>`${quantities[i.id]??0} × ${i.name}`).join('\n');const href=contactHref('whatsapp',restaurant.whatsapp,`Hello! I'd like to order:\n${text}\nMenu subtotal: ${formatCAD(total)} CAD`);if(href){window.open(href,'_blank','noopener,noreferrer');}else setOrderMessage('Your selection is ready, but online ordering is not connected yet. No order has been placed and no payment has been taken.');};
 return <ActionContext.Provider value={{order,contact}}>
  <header className="site-header">
   <Brand/>
   <nav className="desktop-nav" aria-label="Main navigation">{nav.map(n=><Link key={n.to} to={n.to} activeOptions={{exact:true}} activeProps={{className:'nav-link active'}} className="nav-link">{n.label}</Link>)}</nav>
   <div className="header-actions"><Button variant="ghost" size="icon" className="call-header" aria-label="Call the restaurant" title="Call the restaurant" onClick={()=>contact('phone')}><Phone/></Button><Button variant="restaurant" className="order-header" onClick={()=>order()}><ShoppingBag/> Order Now</Button><Button variant="ghost" size="icon" className="mobile-menu-button" aria-label={mobile?'Close navigation':'Open navigation'} aria-expanded={mobile} aria-controls="mobile-navigation" onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</Button></div>
   {mobile&&<nav id="mobile-navigation" className="mobile-nav" aria-label="Mobile navigation">{nav.map(n=><Link key={n.to} to={n.to} activeOptions={{exact:true}} activeProps={{className:'nav-link active'}} className="nav-link" onClick={()=>setMobile(false)}>{n.label}</Link>)}</nav>}
  </header>
  <main>{children}</main>
  <Footer/>
  <Button className="whatsapp-float" size="icon" aria-label="Contact on WhatsApp" title="Contact on WhatsApp" onClick={()=>contact('whatsapp')}><MessageCircle/></Button>
  <Dialog open={orderOpen} onOpenChange={setOrderOpen}><DialogContent className="order-dialog max-w-lg"><DialogHeader><DialogTitle className="text-3xl">A little Punjab, to go.</DialogTitle><DialogDescription>Choose your favourites. Sample menu prices in CAD.</DialogDescription></DialogHeader><div className="order-list">{menuItems.map(i=><div key={i.id} className="order-row"><div><h3>{i.name}</h3><p>{formatCAD(i.price)} CAD</p></div><div className="quantity"><Button variant="outline" size="icon" aria-label={`Remove one ${i.name}`} disabled={!quantities[i.id]} onClick={()=>change(i.id,-1)}><Minus/></Button><span className="w-5 text-center text-sm">{quantities[i.id]??0}</span><Button variant="outline" size="icon" aria-label={`Add one ${i.name}`} onClick={()=>change(i.id,1)}><Plus/></Button></div></div>)}</div><div className="order-total"><span>Menu subtotal</span><span>{formatCAD(total)} CAD</span></div><p className="notice m-0">Sample menu. Final pricing, taxes and availability must be confirmed by the restaurant.</p><div className="order-contact-actions"><Button variant="restaurant" disabled={total===0} onClick={sendOrder}><MessageCircle/> Order via WhatsApp <ArrowRight/></Button><Button variant="outline" onClick={()=>contact('phone')}><Phone/> Call to Order</Button></div>{orderMessage&&<p role="status" className="form-feedback m-0">{orderMessage}</p>}</DialogContent></Dialog>
  <Dialog open={contactMethod!==null} onOpenChange={open=>{if(!open)setContactMethod(null);}}><DialogContent><DialogHeader><DialogTitle className="text-3xl">Let’s get in touch.</DialogTitle><DialogDescription>{contactMethod==='phone'?'The restaurant’s phone number':'The restaurant’s WhatsApp number'} hasn’t been added yet. Please check back for direct contact details.</DialogDescription></DialogHeader><Button asChild variant="restaurant" onClick={()=>setContactMethod(null)}><Link to="/contact">Contact page <ArrowRight/></Link></Button></DialogContent></Dialog>
 </ActionContext.Provider>;
}

function Brand(){return <Link to="/" className="brand" aria-label="Punjab Tadka Toronto home"><span className="brand-mark"><Flame size={25} strokeWidth={1.3}/></span><span><span className="brand-name">Punjab Tadka</span><span className="brand-city">Toronto · Punjabi kitchen</span></span></Link>;}
function Footer(){return <footer className="site-footer"><div className="container"><div className="footer-grid"><div><Brand/><p>Rooted in Punjab. Made for Toronto.<br/>Good food. Warm hearts. Always.</p></div><nav className="footer-links" aria-label="Footer navigation">{nav.slice(1).map(n=><Link key={n.to} to={n.to}>{n.label}</Link>)}</nav><div><div className="flex items-center gap-2 text-sm"><MapPin size={15}/>{restaurant.city}</div><p>Dine-in · Takeout · Punjabi hospitality</p></div></div><div className="footer-bottom"><span>© 2026 Punjab Tadka Toronto. All rights reserved.</span><span>Made with a little extra tadka.</span></div></div></footer>;}

export function HomePage(){const {order}=useActions();return <>
 <section className="hero"><img className="hero-image" src={images.feast} alt="A Punjabi feast of butter chicken, tandoori chicken, naan and biryani" width={1920} height={1024} fetchPriority="high"/><div className="container hero-content reveal"><div className="eyebrow">{restaurant.heroEyebrow}</div><h1>{restaurant.heroTitle}<br/><em>{restaurant.heroAccent}</em></h1><p>{restaurant.heroDescription}</p><div className="hero-buttons"><Button variant="restaurant" size="lg" onClick={()=>order()}><ShoppingBag/> Order Now <ArrowRight/></Button><Button asChild variant="hero" size="lg"><Link to="/menu">Explore Our Menu <ArrowUpRight/></Link></Button></div><div className="hero-note"><MapPin size={14}/><span>Toronto, Canada</span><span>·</span><span>Dine-in & takeout</span></div></div><span className="hero-caption">Big flavours. Beautifully shared.</span></section>
 <TrustBand/>
 <section className="section-tight"><div className="container intro"><div><div className="eyebrow">A warm Punjabi welcome</div><h2>From Punjab,<br/>with love.</h2></div><div><p>{restaurant.introText}</p><Button asChild variant="link" className="p-0 h-auto"><Link to="/about">Our story <ArrowRight/></Link></Button></div></div></section>
 <section className="section pt-5"><div className="container"><SectionHeading eyebrow="The crowd favourites" title="A taste of Punjab." description="The dishes you’ll come back for. Crafted with spice, served with love." link="/menu" linkText="View Full Menu"/><div className="menu-grid">{menuItems.slice(0,3).map(item=><FoodCard key={item.id} item={item}/>)}</div><p className="menu-footnote">All prices in CAD. Sample menu and prices; please confirm with the restaurant.</p></div></section>
 <StorySection/>
 <section className="section"><div className="container"><SectionHeading eyebrow="Fresh from our kitchen" title="Feast your eyes." description="A little glimpse of the flavours waiting for you." link="/gallery" linkText="View Gallery"/><GalleryGrid/></div></section>
 <section className="section section-tinted"><div className="container"><SectionHeading eyebrow="There’s a place for you" title="Come hungry. Leave happy." description="A warm welcome and your Punjabi favourites, right here in Toronto."/><VisitSection/></div></section>
 </>;}
function TrustBand(){return <div className="trust-band"><div className="container trust-inner"><span className="trust-item"><UtensilsCrossed/>Authentic Punjabi recipes</span><span className="trust-item"><Flame/>Fresh from the tandoor</span><span className="trust-item"><Leaf/>Vegetarian favourites</span><span className="trust-item"><ShoppingBag/>Dine-in & takeout</span></div></div>;}
function SectionHeading({eyebrow,title,description,link,linkText}:{eyebrow:string;title:string;description?:string;link?:'/menu'|'/gallery';linkText?:string}){return <div className="section-heading"><div><div className="eyebrow">{eyebrow}</div><h2>{title}</h2>{description&&<p>{description}</p>}</div>{link&&<Button asChild variant="link" className="shrink-0"><Link to={link}>{linkText}<ArrowRight/></Link></Button>}</div>;}
function FoodCard({item}:{item:MenuItem}){const {order}=useActions();return <article className="food-card"><div className="food-image-wrap"><img className="food-image" src={item.image} alt={item.name} width={1024} height={1024} loading="lazy"/><span className="food-badge">{item.vegetarian?<Leaf size={11}/>:<Sparkles size={11}/>} {item.tag}</span></div><div className="food-card-body"><div className="food-card-top"><h3>{item.name}</h3><span className="food-price">{formatCAD(item.price)}<small>CAD</small></span></div><p>{item.description}</p><div className="food-card-bottom"><span>{item.vegetarian?'Vegetarian':item.category==='Tandoor'?'Smoky & spiced':'Rich & comforting'}</span><Button variant="link" className="p-0 h-auto text-xs" onClick={()=>order(item.id)}>Order dish <ArrowUpRight/></Button></div></div></article>;}
export function StorySection(){return <section className="section section-tinted"><div className="container story-layout"><img src={images.feast} alt="Traditional Punjabi dishes served in copper bowls" className="story-image" width={1920} height={1024} loading="lazy"/><div className="story-copy"><div className="eyebrow">Our roots. Your table.</div><h2>Punjabi soul.<br/>Toronto heart.</h2><p>In Punjab, food is more than a meal. It’s a welcome, a celebration, a way of saying you belong. That spirit is at the heart of Punjab Tadka Toronto.</p><p>Our menu celebrates the classics: the comfort of butter chicken, the smoky character of the tandoor, and vegetarian dishes full of colour and flavour. Familiar favourites, prepared with care and shared with warmth.</p><div className="story-signature">A little taste of home, in every bite.</div></div></div></section>;}
function GalleryGrid(){const [selected,setSelected]=useState<{src:string;name:string}|null>(null);const photos=[{src:images.butter,name:'Butter Chicken'},{src:images.tandoori,name:'Tandoori Chicken'},{src:images.chole,name:'Chole Bhature'},{src:images.paneer,name:'Paneer Tikka'},{src:images.naan,name:'Garlic Naan'},{src:images.biryani,name:'Chicken Biryani'}];return <><div className="gallery-grid">{photos.map(p=><Button key={p.name} variant="ghost" className="gallery-item" aria-label={`View ${p.name} photo`} onClick={()=>setSelected(p)}><img src={p.src} alt={p.name} width={1024} height={1024} loading="lazy"/><span>{p.name}</span></Button>)}</div><Dialog open={selected!==null} onOpenChange={o=>{if(!o)setSelected(null);}}><DialogContent className="max-w-3xl"><DialogHeader><DialogTitle>{selected?.name}</DialogTitle><DialogDescription>From our Punjabi-inspired food collection.</DialogDescription></DialogHeader>{selected&&<img src={selected.src} alt={selected.name} width={1024} height={1024} className="lightbox-image"/>}</DialogContent></Dialog></>;}
function PageTitle({eyebrow,title,description}:{eyebrow:string;title:string;description:string}){return <div className="page-title"><div className="container reveal"><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{description}</p></div></div>;}
export function MenuPage(){const [filter,setFilter]=useState('All dishes');const categories=['All dishes','Curries','Tandoor','Vegetarian','Breads & Rice'];return <><PageTitle eyebrow="Made with love. Finished with tadka." title="Our Menu" description="Punjabi classics, tandoor favourites, and something for everyone."/><section className="section"><div className="container"><div className="filters" aria-label="Menu categories">{categories.map(c=><Button key={c} variant={filter===c?'olive':'outline'} onClick={()=>setFilter(c)} aria-pressed={filter===c}>{c}</Button>)}</div><div className="menu-grid">{menuItems.filter(i=>filter==='All dishes'||(filter==='Vegetarian'?i.vegetarian:i.category===filter)).map(i=><FoodCard key={i.id} item={i}/>)}</div><p className="menu-footnote">Sample menu · All prices in CAD · Please confirm prices and availability with the restaurant.<br/>Please speak with the restaurant about allergies before ordering.</p></div></section></>;}
export function GalleryPage(){return <><PageTitle eyebrow="Colour. Spice. A little temptation." title="Food Gallery" description="A closer look at our Punjabi favourites. Made to be shared."/><section className="section"><div className="container"><GalleryGrid/><div className="mt-5"><img src={images.feast} alt="A full Punjabi feast with curry, naan, paneer and biryani" width={1920} height={1024} loading="lazy" className="w-full rounded-sm"/></div></div></section></>;}
export function AboutPage(){return <><PageTitle eyebrow="The heart behind the flavour" title="Our Story" description="Rooted in Punjabi tradition. At home in Toronto."/><StorySection/><section className="section"><div className="container intro"><div><div className="eyebrow">Good food brings us together</div><h2>A table full of flavour.<br/>A welcome full of heart.</h2></div><div><p>{restaurant.introText}</p><p>Whether you’re dropping in for your favourite curry or bringing home a feast for the family, there’s always room for a little more tadka.</p><Button asChild variant="restaurant"><Link to="/menu">Find your favourite <ArrowRight/></Link></Button></div></div></section><TrustBand/></>;}
function VisitSection(){const {contact}=useActions();const key=import.meta.env['VITE_LOVABLE_CONNECTOR_GOOGLE_MAPS_BROWSER_KEY'];return <div className="visit-grid"><div><div className="visit-detail"><MapPin/><div><strong>{restaurant.name}</strong><br/>{restaurant.address||restaurant.city}{!restaurant.address&&<p className="notice m-0">Street address to be confirmed.</p>}</div></div><div className="visit-detail"><Clock3/><div className="w-full"><strong>Opening hours</strong>{restaurant.hours.map(h=><div className="hours-row" key={h.days}><span>{h.days}</span><span>{h.time}</span></div>)}<p className="notice m-0">Sample hours · Please confirm before visiting.</p></div></div><div className="contact-details"><p><strong>Phone</strong><span>{restaurant.phone||'Number to be confirmed'}</span></p><p><strong>WhatsApp</strong><span>{restaurant.whatsapp||'Number to be confirmed'}</span></p><p><strong>Email</strong>{restaurant.email?<a href={`mailto:${restaurant.email}`}>{restaurant.email}</a>:<span>Email to be confirmed</span>}</p></div><div className="flex flex-wrap gap-3 mt-5"><Button variant="restaurant" onClick={()=>contact('phone')}><Phone/> Call to Order</Button><Button variant="outline" onClick={()=>contact('whatsapp')}><MessageCircle/> WhatsApp</Button></div></div><div>{key&&restaurant.address?<iframe className="map-frame" loading="lazy" title="Punjab Tadka Toronto location on Google Maps" referrerPolicy="no-referrer" src={`https://www.google.com/maps/embed/v1/place?key=${key}&q=${encodeURIComponent(restaurant.address)}`}/>:<div className="location-panel"><MapPin className="text-primary" size={34} strokeWidth={1.3}/><h3>A taste of Punjab in Toronto.</h3><p>{restaurant.address||'Toronto, Ontario, Canada'}<br/>{!restaurant.address&&'Our exact location will be added soon.'}</p><Button asChild variant="outline"><a target="_blank" rel="noopener noreferrer" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(restaurant.address||'Toronto Ontario Canada')}`}>{restaurant.address?'Get Directions':'Explore Toronto on Maps'} <ArrowUpRight/></a></Button></div>}</div></div>;}
export function ContactPage(){const [feedback,setFeedback]=useState('');const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const data=new FormData(event.currentTarget);if(restaurant.email){const subject=encodeURIComponent(`Website enquiry from ${data.get('name')}`);const body=encodeURIComponent(`Name: ${data.get('name')}\nEmail: ${data.get('email')}\nPhone: ${data.get('phone')}\n\n${data.get('message')}`);window.location.href=`mailto:${restaurant.email}?subject=${subject}&body=${body}`;setFeedback('Your email app will open with your message. Send it there to complete your enquiry.');}else setFeedback('Your message has not been sent. The restaurant’s contact email is not connected yet; please check back for contact details.');};return <><PageTitle eyebrow="We’d love to hear from you" title="Let’s Talk" description="A question, a family gathering, or your next Punjabi feast. Get in touch."/><section className="section"><div className="container"><VisitSection/></div></section><section className="section section-tinted"><div className="container visit-grid"><div><div className="eyebrow">Drop us a line</div><h2>Good conversations<br/>start here.</h2><p className="text-sm text-muted-foreground leading-7">For menu enquiries, group dining, or a little more information, leave us a message.</p>{!restaurant.email&&<p className="notice">Contact delivery is not connected yet. Messages cannot be sent until the restaurant’s email is added.</p>}</div><form className="contact-form" onSubmit={submit}><div className="form-row"><label>Your name<input name="name" autoComplete="name" placeholder="Full name" required maxLength={100}/></label><label>Email address<input name="email" type="email" autoComplete="email" placeholder="you@example.com" required maxLength={254}/></label></div><label>Phone number (optional)<input name="phone" type="tel" autoComplete="tel" placeholder="Your phone number" maxLength={30}/></label><label>Your message<textarea name="message" placeholder="What’s on your mind?" required maxLength={3000}/></label><Button variant="restaurant" className="justify-self-start" type="submit">Send Message <ArrowRight/></Button>{feedback&&<p className="form-feedback" role="status">{feedback}</p>}</form></div></section></>;}
